image: docker.x32.cz/tools/runner

variables:
    IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}

stages:
    - test
    - publish

test:
    stage: test
    script:
        - docker build --pull -t ${IMAGE} -f ./.docker/Dockerfile . >/dev/null 2>&1
        - docker-compose -f .docker/dc.test.yml up -d >/dev/null 2>&1
        - docker exec ${CI_COMMIT_SHA} ./test.sh
    after_script:
        - docker-compose -f .docker/dc.test.yml down --volumes >/dev/null 2>&1

github sync:
    stage: publish
    variables:
        GIT_STRATEGY: none
    script:
        - git clone --mirror $CI_REPOSITORY_URL edde.git
        - cd edde.git
        - git push --mirror https://$GITHUB_TOKEN@github.com/edde-framework/edde.git
    only:
        - master
        - tags
        - /^v.*$/
