image: docker:latest

variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    PROJECT: edde

before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

stages:
    - test
    - deploy
    - publish

test:
    stage: test
    script:
        - apk add -U py-pip >/dev/null 2>&1
        - pip install docker-compose >/dev/null 2>&1
        - docker build -t $CI_COMMIT_REF_NAME --file .docker/Dockerfile . >/dev/null 2>&1
        - docker-compose -f .docker/dc.test.yml up -d >/dev/null 2>&1
        - docker exec $CI_COMMIT_REF_NAME ./test.sh
    after_script:
        - docker-compose -f .docker/dc.test.yml down --volumes >/dev/null 2>&1

deploy web:
    stage: deploy
    variables:
        FQDN: edde-framework.org
    script:
        - docker build --pull -t $IMAGE -f ./.docker/Dockerfile .
        - docker push $IMAGE
        - docker stack deploy --with-registry-auth --prune -c ./.docker/dc.production.yml $PROJECT-production
    environment:
        name: production
        url: https://edde-framework.org

github sync:
    stage: publish
    variables:
        GIT_STRATEGY: none
    script:
    - apk add -U git >/dev/null 2>&1
    - git clone --mirror $CI_REPOSITORY_URL edde.git
    - cd edde.git
    - git push --mirror https://$GITHUB_TOKEN@github.com/edde-framework/edde.git
    only:
    - master
    - tags
    - /^v.*$/
