image: docker:latest

variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    PROJECT: edde

before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

stages:
    - build
    - test
    - review
    - deploy
    - publish

build:
    stage: build
    script:
        - docker build --pull -t ${IMAGE} -f ./.docker/Dockerfile . >/dev/null 2>&1
        - docker push ${IMAGE}

test:
    stage: test
    script:
        - apk add -U py-pip >/dev/null 2>&1
        - pip install docker-compose >/dev/null 2>&1
        - docker-compose -f .docker/dc.test.yml up -d >/dev/null 2>&1
        - docker exec ${CI_COMMIT_REF_NAME} ./test.sh
    after_script:
        - docker-compose -f .docker/dc.test.yml down --volumes >/dev/null 2>&1

start review:
    stage: review
    variables:
        FQDN: ${CI_ENVIRONMENT_SLUG}.edde-framework.org
    script:
        - docker stack deploy --with-registry-auth --prune -c ./.docker/dc.review.yml $PROJECT-$CI_ENVIRONMENT_SLUG
    environment:
        name: review/$CI_COMMIT_REF_NAME
        url: http://${CI_ENVIRONMENT_SLUG}.edde-framework.org
        on_stop: stop review
    only:
        - branches
    except:
        - master

stop review:
    stage: review
    variables:
        FQDN: ${CI_ENVIRONMENT_SLUG}.edde-framework.org
        GIT_STRATEGY: none
    script:
        - docker stack rm $PROJECT-$CI_ENVIRONMENT_SLUG
    environment:
        name: review/$CI_COMMIT_REF_NAME
        url: http://${CI_ENVIRONMENT_SLUG}.edde-framework.org
        action: stop
    when: manual
    only:
        - branches
    except:
        - master

deploy web:
    stage: deploy
    variables:
        FQDN: edde-framework.org
    script:
        - docker build --pull -t $IMAGE -f ./.docker/Dockerfile .
        - docker push $IMAGE
        - docker stack deploy --with-registry-auth --prune -c ./.docker/dc.production.yml $PROJECT-production
    environment:
        name: production
        url: https://edde-framework.org
    only:
        - master

github sync:
    stage: publish
    variables:
        GIT_STRATEGY: none
    script:
        - apk add -U git >/dev/null 2>&1
        - git clone --mirror $CI_REPOSITORY_URL edde.git
        - cd edde.git
        - git push --mirror https://$GITHUB_TOKEN@github.com/edde-framework/edde.git
    only:
        - master
        - tags
        - /^v.*$/
