image: docker:latest

variables:
    PROJECT: edde

stages:
    - test
    - release

test:
    stage: test
    script:
        - apk add -U py-pip >/dev/null 2>&1
        - pip install docker-compose >/dev/null 2>&1
        - docker build -t edde --file .docker/Dockerfile .
        - docker-compose -f dc.test.yml up -d
        - docker exec -it edde lib/bin/phpunit
        - docker-compose -f .docker/dc.test.yml down --volumes >/dev/null 2>&1

github sync:
    stage: release
    script:
        - apk add -U git >/dev/null 2>&1
        - git clone --mirror $CI_REPOSITORY_URL edde.git
        - cd edde.git
        - git push --mirror https://$GITHUB_TOKEN@github.com/edde-framework/edde.git
    only:
        - master
        - tags
