image: docker:latest

stages:
    - test
    - publish

test:
    stage: test
    script:
        - apk add -U py-pip >/dev/null 2>&1
        - pip install docker-compose >/dev/null 2>&1
        - docker build -t $CI_COMMIT_REF_NAME --file .docker/Dockerfile . >/dev/null 2>&1
        - docker-compose -f .docker/dc.test.yml up -d >/dev/null 2>&1
        - docker exec $CI_COMMIT_REF_NAME ./test.sh
        - ls -la .
        - docker-compose -f .docker/dc.test.yml down --volumes >/dev/null 2>&1

github sync:
    stage: publish
    script:
        - apk add -U git >/dev/null 2>&1
        - git clone --mirror $CI_REPOSITORY_URL edde.git
        - cd edde.git
        - git push --mirror https://$GITHUB_TOKEN@github.com/edde-framework/edde.git
    only:
        - master
        - tags
