version: '2'
services:
  # a client is the routing service for the server (nginx routing everything non-existent to the php-fpm)
  # this service is also used for testing http based subsystems
  client:
    build:
      context: ./
      dockerfile: ./.docker/client/Dockerfile
    ports:
      - "80:80"
    working_dir: /client
    volumes:
      - ./client:/client
      - ./.docker/client/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - client-server-network

  # the client server mapping provides direct access to php engine, there are no static files, so everything is routed
  # directly into php; this service should not be called directly; only by a client
  client-server:
    build:
      context: ./
      dockerfile: ./.docker/client-server/Dockerfile
    ports:
      - "32768:80"
    volumes:
      - ./.docker/client-server/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - client-server-network
      - server-network

  # just fast-cgi php engine; server side implementation
  server:
    build:
      context: ./
      dockerfile: ./.docker/server/Dockerfile
    working_dir: /server
    environment:
      - "HOST_IP=${HOST_IP}"
    volumes:
      - .:/server
      - ./.docker/server/xdebug.ini:/etc/php/7.1/fpm/conf.d/21-xdebug-custom.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/10-opcache.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-apcu.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-apcu_bc.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-ftp.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-gettext.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-sysvmsg.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-sysvsem.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-sysvshm.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-wddx.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-xmlreader.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-xmlwriter.ini
      - ./.docker/server/mod-disable.ini:/etc/php/7.1/fpm/conf.d/20-readline.ini
    networks:
      - server-network
#      - redis-network
#      - neo4j-network
#
#  redis:
#    build:
#      context: ./redis
#      dockerfile: ./.docker/Dockerfile
#    networks:
#      - redis-network
#
#  neo4j:
#    image: neo4j:3.2
#    volumes:
#      - ./.storage/neo4j:/data
#    environment:
#      - NEO4J_AUTH=none
#    ports:
#      - "17474:7474"
#      - "17473:7473"
#      - "17687:7687"
#    networks:
#      - neo4j-network
#
networks:
  server-network:
    driver: bridge
  client-server-network:
    driver: bridge
#  redis-network:
#    driver: bridge
#  neo4j-network:
#    driver: bridge
