version: '2'
services:
        edde:
                image: edde
                container_name: edde
                environment:
                    - XDEBUG_IP=$XDEBUG_IP
                    - PHP_IDE_CONFIG=serverName=edde
                volumes:
                    - ../:/edde
                    - ./xdebug.ini:/etc/php7/conf.d/xdebug.ini
                ports:
                    - "4822:22"
                networks:
                    - edde-network
                depends_on:
                    - neo4j
                    - postgres
                    - mysql

        neo4j:
                image: neo4j:3.3-enterprise
                environment:
                    - NEO4J_AUTH=neo4j/eeQFXk7kkqSm
                    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
                ports:
                    - "17474:7474"
                    - "17687:7687"
                networks:
                    - edde-network

        postgres:
            image: postgres:latest
            environment:
                - POSTGRES_USER=edde
                - POSTGRES_PASSWORD=PBXxSgEWY3LT
            networks:
                - edde-network

        mysql:
            image: mariadb:latest
            environment:
                - MYSQL_ROOT_PASSWORD=enPUxu8SRctV
                - MYSQL_DATABASE=edde
                - MYSQL_USER=edde
                - MYSQL_PASSWORD=enPUxu8SRctV
            networks:
                - edde-network

        adminer:
            image: adminer:latest
            ports:
                - "18080:8080"
            networks:
                - edde-network

networks:
        edde-network:
