version: '2'
services:
        edde:
                image: edde
                container_name: edde
                environment:
                    - XDEBUG_IP=$XDEBUG_IP
                    - PHP_IDE_CONFIG=serverName=edde
                volumes:
                    - ../:/edde
                ports:
                    - "5480:80"
                    - "4722:22"
                networks:
                    - edde-network

        edde-postgres:
            image: postgres:latest
            environment:
                - POSTGRES_USER=edde
                - POSTGRES_PASSWORD=PBXxSgEWY3LT
            networks:
                - edde-network

        edde-mysql:
            image: mariadb:latest
            environment:
                - MYSQL_ROOT_PASSWORD=enPUxu8SRctV
                - MYSQL_DATABASE=edde
                - MYSQL_USER=edde
                - MYSQL_PASSWORD=enPUxu8SRctV
            networks:
                - edde-network

        adminer:
            image: adminer:latest
            ports:
                - "8080:8080"
            networks:
                - edde-network

networks:
        edde-network:
