version: '3'
services:
    edde:
        image: ${IMAGE}
        networks:
            - proxy
        deploy:
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                - com.df.letsencrypt.host=$FQDN
                - com.df.letsencrypt.email=ssl@$FQDN
                - com.df.serviceDomain=$FQDN
                - com.df.servicePath=/
                - com.df.srcPort=80,443
                - com.df.port=80
                - com.df.httpsOnly=true

networks:
    proxy:
        external: true
