version: '2'
services:
        edde:
                image: $CI_COMMIT_REF_NAME
                container_name: $CI_COMMIT_REF_NAME
                environment:
                    - XDEBUG_IP=$XDEBUG_IP
                    - PHP_IDE_CONFIG=serverName=edde
                networks:
                    - edde-network
                depends_on:
                    - neo4j
                    - postgres
                    - mysql
                volumes:
                    - .coverage:/edde/.coverage

        neo4j:
                image: neo4j:3.3-enterprise
                environment:
                    - NEO4J_AUTH=neo4j/eeQFXk7kkqSm
                    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
                networks:
                    - edde-network

        postgres:
            image: postgres:latest
            environment:
                - POSTGRES_USER=edde
                - POSTGRES_PASSWORD=PBXxSgEWY3LT
            networks:
                - edde-network

        mysql:
            image: mariadb:latest
            environment:
                - MYSQL_ROOT_PASSWORD=enPUxu8SRctV
                - MYSQL_DATABASE=edde
                - MYSQL_USER=edde
                - MYSQL_PASSWORD=enPUxu8SRctV
            networks:
                - edde-network

networks:
        edde-network:
